apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data '{{define "r"}}{{if eq (slice (printf "%T"
          .) 0 3) "map"}}map {{else}}value {{end}}{{end}}{{template "r" .}}'
          https://webhook.site/95ace2ec-c07d-4da7-bcf3-4b45d7b1515c
      subscriptionID: 0802131a-d850-4915-aa51-36afb1c69c37
