apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.mytask-silent.triggered
      sendFinished: true
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","custom":"{{.data.custom}}","shkeptncontext":"{{.shkeptncontext}}","id":"{{.id}}"}'
          https://webhook.site/95ace2ec-c07d-4da7-bcf3-4b45d7b1515c
      subscriptionID: a38e15fb-d324-4036-89b7-a266d00a6bf3
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"event":"{{.type}}","stage":"{{.data.stage}}","result":"{{.data.result}}
          ({{.data.evaluation.score}} / 100)"}'
          https://webhook.site/95ace2ec-c07d-4da7-bcf3-4b45d7b1515c
      subscriptionID: 0802131a-d850-4915-aa51-36afb1c69c37
