apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --request POST --data '{{define \"r\"}}  {{if eq (slice (printf
          \"%T\" .) 0 3) \"map\"}}    { {{range $k, $v := .}}      \"{{$k}}\":
          {{template \"r\" $v}},    {{end}} }  {{else}}    {{if eq (slice
          (printf \"%T\" .) 0 2) \"[]\"}}      [ {{range .}}{{template \"r\"
          .}}, {{end}} ]    {{else}}      {{if eq (slice (printf \"%T\" .)  0 3)
          \"str\"}}        {{. | printf \"%q\"}}      {{else}}        {{if eq
          (slice (printf \"%T\" .)  0 3) \"boo\"}}          {{if
          .}}true{{else}}false{{end}}        {{else}}          \"{{. | printf
          \"%T\" |
          js}}\"        {{end}}      {{end}}    {{end}}  {{end}}{{end}}{ {{range
          $k, $v := .}}  \"{{$k}}\": {{template \"r\" $v}},{{end}} }'
          https://webhook.site/95ace2ec-c07d-4da7-bcf3-4b45d7b1515c"
      subscriptionID: 0802131a-d850-4915-aa51-36afb1c69c37
